spring:
  datasource:
    username: root
    password: 1997wxc
    url: jdbc:mysql://localhost:3306/manage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver